#!/usr/bin/env bash
# Wyrdsekai Relay — Bare Metal Setup Script
#
# Installs NATS server, generates auth token, configures TLS,
# and creates a systemd service for the relay.
#
# Usage:
#   chmod +x setup.sh
#   sudo ./setup.sh
#

set -euo pipefail

NATS_VERSION="2.10.24"
NATS_ARCH="linux-amd64"
NATS_URL="https://github.com/nats-io/nats-server/releases/download/v${NATS_VERSION}/nats-server-v${NATS_VERSION}-${NATS_ARCH}.tar.gz"
CONF_DIR="/etc/nats"
LOG_DIR="/var/log/nats"

# #20 (2026-07-19 OSS hardening) — honor WYRD_RELAY_PORT_OFFSET like the
# canonical packaging/relay.sh, so co-locating multiple relay legs on one host
# doesn't collide on the fixed ports. Was hardcoded 4222/9222/8222.
PORT_OFFSET="${WYRD_RELAY_PORT_OFFSET:-0}"
NATS_PORT=$((4222 + PORT_OFFSET))   # public zone-leg
WS_PORT=$((9222 + PORT_OFFSET))     # internal NATS websocket
MON_PORT=$((8222 + PORT_OFFSET))    # loopback NATS monitor

echo "=== Wyrdsekai Relay Setup ==="
echo ""

# Check for root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root (or with sudo)."
    exit 1
fi

# 1. Install nats-server
echo "Installing NATS server v${NATS_VERSION}..."
if command -v nats-server &>/dev/null; then
    echo "  nats-server already installed: $(nats-server --version)"
else
    curl -fsSL "$NATS_URL" | tar xz
    mv "nats-server-v${NATS_VERSION}-${NATS_ARCH}/nats-server" /usr/local/bin/
    rm -rf "nats-server-v${NATS_VERSION}-${NATS_ARCH}"
    echo "  Installed: $(nats-server --version)"
fi

# 2. Generate auth token (256-bit random, base64url)
TOKEN=$(openssl rand -base64 32 | tr -d '=/+')
echo ""
echo "Generated household token: $TOKEN"
echo ""

# 3. Get domain
read -rp "Enter your domain name (or press Enter for IP-only): " DOMAIN

# 4. Configure TLS
if [ -n "$DOMAIN" ]; then
    echo "Setting up TLS via Let's Encrypt for $DOMAIN..."
    if ! command -v certbot &>/dev/null; then
        apt-get update -qq
        apt-get install -y -qq certbot
    fi
    certbot certonly --standalone -d "$DOMAIN" --non-interactive --agree-tos -m "admin@$DOMAIN"
    CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
    TLS_CONFIG="
websocket {
    listen: \"0.0.0.0:${WS_PORT}\"
    tls {
        cert_file: \"$CERT_PATH/fullchain.pem\"
        key_file: \"$CERT_PATH/privkey.pem\"
    }
}"
    RELAY_URL="wss://$DOMAIN:${WS_PORT}"
else
    TLS_CONFIG="
websocket {
    listen: \"0.0.0.0:${WS_PORT}\"
    no_tls: true
}"
    echo "WARNING: No TLS configured. Use a reverse proxy (Caddy/nginx) for production."
    RELAY_URL="ws://$(curl -s ifconfig.me):${WS_PORT}"
fi

# 5. Write config
mkdir -p "$CONF_DIR"
mkdir -p "$LOG_DIR"

cat > "$CONF_DIR/relay.conf" << CONF
# Wyrdsekai Relay — Auto-generated by setup.sh
listen: 0.0.0.0:${NATS_PORT}
# Localhost-only HTTP monitoring — the registration sidecar's liveness reaper
# polls /connz here; never exposed publicly.
http: "127.0.0.1:${MON_PORT}"
$TLS_CONFIG
authorization {
    users = [
        { user: "household", password: "$TOKEN" }
    ]
}
max_payload: 65536
max_connections: 100
max_control_line: 4096
log_file: "$LOG_DIR/relay.log"
log_size_limit: 10485760
CONF

echo "Config written to $CONF_DIR/relay.conf"

# 6. Create systemd service
cat > /etc/systemd/system/wyrd-relay.service << SERVICE
[Unit]
Description=Wyrdsekai NATS Relay
After=network.target

[Service]
ExecStart=/usr/local/bin/nats-server -c $CONF_DIR/relay.conf
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable wyrd-relay
systemctl start wyrd-relay

echo ""
echo "=== Relay is running ==="
echo "URL:   $RELAY_URL"
echo "Token: $TOKEN"
echo ""
echo "Enter these in your household server settings under:"
echo "  Remote Access -> Self-hosted relay"
echo ""
echo "To add more households, edit $CONF_DIR/relay.conf and run:"
echo "  systemctl reload wyrd-relay"
