package org.wyrdsekai.between;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

/**
 * builder for a NATS leaf-node-mode config so any
 * node with sufficient resources can act as a per-zone relay hub.
 *
 * <p>The household scale problem: with a single central public relay, all
 * cross-zone traffic plus intra-zone fan-out funnels through one server. As
 * households grow, that hot-spot becomes the bottleneck. NATS already solves
 * this with leaf-nodes — a downstream NATS server connects upstream as a
 * "leaf", forwards a subset of subjects in both directions, and absorbs
 * intra-zone traffic locally.</p>
 *
 * <p>This class is the config generator: feed it the zone tag, the upstream
 * relay URL, and the local NKey identity, get back a NATS config that boots a
 * leaf-mode server. {@code BetweenActor} wires this when
 * {@code WYRDSEKAI_RELAY_ENABLED=true}. The wyrd CLI shows the operator how
 * to start the embedded NATS with this config.</p>
 *
 * <p>Subject scoping: only {@code between.{householdTag}.>} +
 * {@code federation.{zoneId}.gate.>} flow over the leaf link. High-frequency
 * intra-zone heartbeats and primaries stay local. Symmetric to RelayBridge's
 * existing forwarding rules — leaf-nodes do at the NATS layer what RelayBridge
 * did in Java; this is strictly faster and lets us delete that code path
 * eventually.</p>
 */
public final class LeafRelayConfig {

    private static final Logger log = LoggerFactory.getLogger(LeafRelayConfig.class);

    /**
     * @param leafPort        local NATS leaf port for downstream clients (default 7422)
     * @param clientPort      local NATS client port for in-process actors (default 4222)
     * @param httpMonitorPort optional monitoring port (default 8222), 0 to disable
     * @param upstreamUrl     URL of the parent relay, e.g. nats://relay.example:7422
     * @param householdTag    zone's household tag, scopes between subjects
     * @param zoneId          zone id (for federation gate scoping)
     * @param nkeyPubkey      this leaf's NKey pubkey — used to authenticate
     *                        upstream and (optionally) to gate inbound clients
     * @param trustedClientPubkeys NKey pubkeys allowed to connect TO this leaf
     *                             as clients (other zone-local nodes)
     */
    public record Spec(
        int leafPort,
        int clientPort,
        int httpMonitorPort,
        String upstreamUrl,
        String householdTag,
        String zoneId,
        String nkeyPubkey,
        List<String> trustedClientPubkeys
    ) {
        public Spec {
            if (clientPort <= 0) throw new IllegalArgumentException("clientPort must be > 0");
            if (leafPort <= 0) throw new IllegalArgumentException("leafPort must be > 0");
            if (clientPort == leafPort) {
                throw new IllegalArgumentException(
                    "clientPort and leafPort must differ (got " + clientPort + ")");
            }
            if (upstreamUrl == null || upstreamUrl.isBlank()) {
                throw new IllegalArgumentException("upstreamUrl is required");
            }
            if (nkeyPubkey == null || nkeyPubkey.length() != 56 || !nkeyPubkey.startsWith("U")) {
                throw new IllegalArgumentException("nkeyPubkey must be a 56-char NATS user key");
            }
            trustedClientPubkeys = trustedClientPubkeys == null
                ? List.of()
                : List.copyOf(trustedClientPubkeys);
        }

        /** Default-config builder for the common case. */
        public static Spec defaults(String upstreamUrl, String householdTag, String zoneId,
                                    String nkeyPubkey) {
            return new Spec(7422, 4222, 8222, upstreamUrl, householdTag, zoneId, nkeyPubkey,
                List.of());
        }
    }

    /**
     * Render the NATS config text. Pure function — does not write to disk.
     * Caller decides where the config lives.
     */
    public static String render(Spec spec) {
        var lines = new ArrayList<String>();
        lines.add("# Generated by wyrdsekai LeafRelayConfig");
        lines.add("# Edit the wyrdsekai env to regenerate; do not hand-edit unless you know why.");
        lines.add("");
        lines.add("port: " + spec.clientPort);
        if (spec.httpMonitorPort > 0) {
            lines.add("http_port: " + spec.httpMonitorPort);
        }
        lines.add("server_name: \"wyrdleaf-" + spec.zoneId + "\"");
        lines.add("");

        // Authorization for inbound clients (zone-local nodes connecting to us).
        // Note: the leaf's OWN identity is in the leafnodes.remotes block below;
        // this section only governs who can connect AS A CLIENT.
        if (!spec.trustedClientPubkeys.isEmpty()) {
            lines.add("authorization {");
            lines.add("    users = [");
            for (var pk : spec.trustedClientPubkeys) {
                lines.add("        { nkey: \"" + pk + "\",");
                lines.add("          permissions: {");
                lines.add("            publish:   { allow: [\"between." + spec.householdTag
                    + ".>\", \"federation." + spec.zoneId + ".>\", \"_INBOX.>\"] }");
                lines.add("            subscribe: { allow: [\"between." + spec.householdTag
                    + ".>\", \"federation." + spec.zoneId + ".>\", \"_INBOX.>\"] }");
                lines.add("          }");
                lines.add("        },");
            }
            lines.add("    ]");
            lines.add("}");
            lines.add("");
        }

        // Leafnodes block: connect upstream + accept downstream clients optionally.
        lines.add("leafnodes {");
        lines.add("    port: " + spec.leafPort);
        lines.add("    remotes = [");
        lines.add("        {");
        lines.add("            url: \"" + spec.upstreamUrl + "\"");
        // Subject filters: forward our zone's between + federation gate to upstream
        // and accept the same back. Heartbeats/room-primaries stay local.
        lines.add("            deny_export = [\"between.*.cluster.heartbeat.>\","
            + " \"between.*.room.primary.heartbeat.>\"]");
        lines.add("            deny_import = [\"between.*.cluster.heartbeat.>\","
            + " \"between.*.room.primary.heartbeat.>\"]");
        lines.add("        }");
        lines.add("    ]");
        lines.add("}");
        return String.join("\n", lines) + "\n";
    }

    /**
     * Render and write to disk; create parent dirs as needed.
     * @return the path written to (same as input)
     */
    public static Path writeTo(Path target, Spec spec) throws IOException {
        Files.createDirectories(target.getParent());
        Files.writeString(target, render(spec), StandardCharsets.UTF_8,
            StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        log.info("LeafRelayConfig: wrote leafnode config to {} (upstream={}, leafPort={}, "
            + "clientPort={}, trustedClients={})",
            target, spec.upstreamUrl, spec.leafPort, spec.clientPort,
            spec.trustedClientPubkeys.size());
        return target;
    }

    private LeafRelayConfig() {}
}
