package org.wyrdsekai.between;

import io.nats.client.Connection;
import io.nats.client.Nats;
import io.nats.client.Options;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * integration test: spin up an upstream NATS with a
 * leaf-node listener, start a downstream NATS configured via
 * {@link LeafRelayConfig} as a leaf, publish a {@code between.hh-test.echo}
 * message on the leaf and verify it propagates to the upstream.
 *
 * <p>This is the full leaf-relay flow exercised end-to-end. If the generated
 * NATS config is invalid (typo, missing block, port collision) the test fails
 * fast instead of in production.</p>
 */
@Tag("integration")
@EnabledIf("isNatsServerAvailable")
@Tag("needs-nats")
final class LeafRelayE2EIT {

    static boolean isNatsServerAvailable() {
        return NatsServerManager.isAvailable("nats-server");
    }

    private static final String VALID_PUBKEY =
        "UAMIVSMSJSYT5JOD44IHVDLOJAR6EAGGFBFKEQU4ILYHBKK52IKSUSQT";

    private final List<Process> spawned = new ArrayList<>();

    @AfterEach
    void stop_all_nats() throws Exception {
        for (var p : spawned) {
            p.destroy();
            if (!p.waitFor(5, TimeUnit.SECONDS)) p.destroyForcibly();
        }
        spawned.clear();
    }

    @BeforeEach
    void verify_clean_state() {
        assertThat(spawned).isEmpty();
    }

    @Test
    void leaf_subject_propagates_to_upstream(@TempDir Path tmp) throws Exception {
        // Allocate ports: upstream listens for clients + leaf inbound;
        // downstream listens for clients + tells leaf module to dial upstream.
        int upstreamClient = freePort();
        int upstreamLeaf = freePort();
        int downstreamClient = freePort();
        int downstreamLeaf = freePort();  // not strictly used (no client on downstream's leaf port)

        // Upstream config: open client port + leafnodes listener (no auth for the test).
        var upstreamConf = """
            port: %d
            http_port: 0
            server_name: "upstream-test"
            leafnodes {
                port: %d
            }
            """.formatted(upstreamClient, upstreamLeaf);
        var upstreamConfFile = tmp.resolve("upstream.conf");
        Files.writeString(upstreamConfFile, upstreamConf, StandardCharsets.UTF_8);
        startNats(upstreamConfFile, "upstream");
        waitForNatsHealthy(upstreamClient, Duration.ofSeconds(5));

        // Downstream: generated by LeafRelayConfig pointing at upstream's leaf port.
        var spec = new LeafRelayConfig.Spec(
            downstreamLeaf,                                  // local leaf port (unused here)
            downstreamClient,                                // local client port
            0,                                               // no monitor
            "nats://127.0.0.1:" + upstreamLeaf,              // upstream leaf URL
            "hh-test",
            "alpha",
            VALID_PUBKEY,
            List.of());                                      // no inbound client auth
        var downstreamConfFile = tmp.resolve("downstream.conf");
        LeafRelayConfig.writeTo(downstreamConfFile, spec);

        startNats(downstreamConfFile, "downstream");
        waitForNatsHealthy(downstreamClient, Duration.ofSeconds(5));
        // Allow the leaf connection to establish.
        Thread.sleep(800);

        // Subscribe on UPSTREAM, publish on DOWNSTREAM, expect propagation.
        var upUrl = "nats://127.0.0.1:" + upstreamClient;
        var dnUrl = "nats://127.0.0.1:" + downstreamClient;
        try (Connection up = Nats.connect(new Options.Builder().server(upUrl)
                .connectionTimeout(Duration.ofSeconds(3)).build());
             Connection dn = Nats.connect(new Options.Builder().server(dnUrl)
                .connectionTimeout(Duration.ofSeconds(3)).build())) {

            var queue = new LinkedBlockingQueue<String>();
            var dispatcher = up.createDispatcher(msg ->
                queue.offer(new String(msg.getData(), StandardCharsets.UTF_8)));
            dispatcher.subscribe("between.hh-test.echo");
            // Subscription propagation across leaf can take a beat.
            Thread.sleep(300);

            dn.publish("between.hh-test.echo",
                "leaf-relay-says-hello".getBytes(StandardCharsets.UTF_8));

            var received = queue.poll(5, TimeUnit.SECONDS);
            assertThat(received)
                .as("subject published on downstream should reach upstream subscriber via leaf")
                .isEqualTo("leaf-relay-says-hello");
        }
    }

    @Test
    void heartbeat_subjects_are_denied_across_leaf(@TempDir Path tmp) throws Exception {
        // SPEC §5a invariant: zone-internal heartbeats stay local. Verify that
        // a between.X.cluster.heartbeat publish on downstream does NOT reach
        // upstream (deny_export rule in the generated config).
        int upstreamClient = freePort();
        int upstreamLeaf = freePort();
        int downstreamClient = freePort();
        int downstreamLeaf = freePort();

        var upstreamConf = """
            port: %d
            http_port: 0
            server_name: "upstream-deny-test"
            leafnodes { port: %d }
            """.formatted(upstreamClient, upstreamLeaf);
        var upConfFile = tmp.resolve("upstream-deny.conf");
        Files.writeString(upConfFile, upstreamConf, StandardCharsets.UTF_8);
        startNats(upConfFile, "upstream-deny");
        waitForNatsHealthy(upstreamClient, Duration.ofSeconds(5));

        var spec = new LeafRelayConfig.Spec(
            downstreamLeaf, downstreamClient, 0,
            "nats://127.0.0.1:" + upstreamLeaf,
            "hh-test", "alpha", VALID_PUBKEY, List.of());
        var dnConfFile = tmp.resolve("downstream-deny.conf");
        LeafRelayConfig.writeTo(dnConfFile, spec);
        startNats(dnConfFile, "downstream-deny");
        waitForNatsHealthy(downstreamClient, Duration.ofSeconds(5));
        Thread.sleep(800);

        try (Connection up = Nats.connect(new Options.Builder()
                .server("nats://127.0.0.1:" + upstreamClient)
                .connectionTimeout(Duration.ofSeconds(3)).build());
             Connection dn = Nats.connect(new Options.Builder()
                .server("nats://127.0.0.1:" + downstreamClient)
                .connectionTimeout(Duration.ofSeconds(3)).build())) {

            var queue = new LinkedBlockingQueue<String>();
            up.createDispatcher(msg -> queue.offer(new String(msg.getData())))
                .subscribe("between.hh-test.cluster.heartbeat.>");
            Thread.sleep(300);

            dn.publish("between.hh-test.cluster.heartbeat.alpha-1",
                "leak".getBytes(StandardCharsets.UTF_8));

            var received = queue.poll(2, TimeUnit.SECONDS);
            assertThat(received)
                .as("cluster heartbeat must NOT propagate across leaf — would saturate relay")
                .isNull();
        }
    }

    private void startNats(Path confFile, String tag) throws IOException {
        var p = new ProcessBuilder("nats-server", "-c", confFile.toString())
            .redirectErrorStream(true)
            .start();
        spawned.add(p);
        var drain = new Thread(() -> {
            try (var in = p.getInputStream()) {
                in.transferTo(System.out);
            } catch (IOException ignored) {}
        }, "nats-" + tag + "-drain");
        drain.setDaemon(true);
        drain.start();
    }

    private static int freePort() throws IOException {
        try (var s = new ServerSocket(0)) {
            return s.getLocalPort();
        }
    }

    private static void waitForNatsHealthy(int port, Duration timeout) throws InterruptedException {
        var deadline = System.currentTimeMillis() + timeout.toMillis();
        while (System.currentTimeMillis() < deadline) {
            try (var s = new Socket()) {
                s.connect(new InetSocketAddress("127.0.0.1", port), 200);
                return;
            } catch (IOException ignored) {
                Thread.sleep(100);
            }
        }
        throw new RuntimeException("nats-server didn't accept on " + port);
    }
}
