package org.wyrdsekai.between;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Pure-config tests for {@link LeafRelayConfig}. The end-to-end "spin up a real
 * leaf node, watch a subject propagate" test lives in {@link LeafRelayE2EIT}.
 */
final class LeafRelayConfigTest {

    private static final String VALID_PUBKEY =
        "UAMIVSMSJSYT5JOD44IHVDLOJAR6EAGGFBFKEQU4ILYHBKK52IKSUSQT";  // 56 chars, U-prefix

    @Test
    void spec_rejects_zero_or_negative_ports() {
        assertThatThrownBy(() -> new LeafRelayConfig.Spec(
            0, 4222, 0, "nats://up:7422", "hh-x", "z", VALID_PUBKEY, List.of()))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("leafPort");
        assertThatThrownBy(() -> new LeafRelayConfig.Spec(
            7422, -1, 0, "nats://up:7422", "hh-x", "z", VALID_PUBKEY, List.of()))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("clientPort");
    }

    @Test
    void spec_rejects_invalid_pubkey() {
        assertThatThrownBy(() -> new LeafRelayConfig.Spec(
            7422, 4222, 0, "nats://up:7422", "hh-x", "z", "not-an-nkey", List.of()))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("56-char NATS user key");
    }

    @Test
    void spec_rejects_missing_upstream() {
        assertThatThrownBy(() -> new LeafRelayConfig.Spec(
            7422, 4222, 0, "", "hh-x", "z", VALID_PUBKEY, List.of()))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("upstreamUrl");
    }

    @Test
    void spec_rejects_overlapping_ports() {
        assertThatThrownBy(() -> new LeafRelayConfig.Spec(
            4222, 4222, 0, "nats://up:7422", "hh-x", "z", VALID_PUBKEY, List.of()))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("must differ");
    }

    @Test
    void render_includes_required_blocks() {
        var spec = LeafRelayConfig.Spec.defaults(
            "nats://relay.example:7422", "hh-test", "alpha", VALID_PUBKEY);
        var conf = LeafRelayConfig.render(spec);
        assertThat(conf)
            .as("config must include essential blocks")
            .contains("port: 4222")
            .contains("http_port: 8222")
            .contains("leafnodes {")
            .contains("port: 7422")
            .contains("nats://relay.example:7422")
            .contains("server_name: \"wyrdleaf-alpha\"")
            // Heartbeat exclusion to avoid relay overload
            .contains("deny_export")
            .contains("deny_import");
    }

    @Test
    void render_emits_trusted_client_users_when_specified() {
        var trusted = List.of(
            "UABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ABCDEFGHIJKLMN0XX1",
            "UZYXWVUTSRQPONMLKJIHGFEDCBA0987654321ABCDEFGHIJKLMN0XX2"
        );
        var spec = new LeafRelayConfig.Spec(
            7422, 4222, 8222, "nats://relay:7422",
            "hh-test", "alpha", VALID_PUBKEY, trusted);
        var conf = LeafRelayConfig.render(spec);
        for (var pk : trusted) {
            assertThat(conf).contains("nkey: \"" + pk + "\"");
        }
        // Permissions must be scoped to this household + zone.
        assertThat(conf).contains("between.hh-test.>");
        assertThat(conf).contains("federation.alpha.>");
    }

    @Test
    void writeTo_creates_directories_and_writes_file(@TempDir Path tmp) throws Exception {
        var target = tmp.resolve("nested/dir/relay-leafnode.conf");
        var spec = LeafRelayConfig.Spec.defaults(
            "nats://up:7422", "hh-x", "z", VALID_PUBKEY);
        var written = LeafRelayConfig.writeTo(target, spec);
        assertThat(written).isEqualTo(target);
        assertThat(Files.isRegularFile(target)).isTrue();
        var content = Files.readString(target);
        assertThat(content).contains("leafnodes {");
    }

    @Test
    void writeTo_overwrites_existing_file(@TempDir Path tmp) throws Exception {
        var target = tmp.resolve("conf");
        Files.writeString(target, "# old garbage");
        var spec = LeafRelayConfig.Spec.defaults(
            "nats://up:7422", "hh-x", "z", VALID_PUBKEY);
        LeafRelayConfig.writeTo(target, spec);
        assertThat(Files.readString(target))
            .doesNotContain("old garbage")
            .contains("Generated by wyrdsekai LeafRelayConfig");
    }
}
