package org.wyrdsekai.core.soul;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.wyrdsekai.common.event.WorldEvent;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Extracts the ma (negative space) of an agent's identity:
 * what the agent DIDN'T do is as defining as what it did.
 *
 * Analyzes the gap between events the agent was present for
 * and events the agent responded to. Silence, avoidance,
 * and selective attention are all identity signals.
 */
public final class NegativeSpaceAnalyzer {

    private NegativeSpaceAnalyzer() {}

    /**
     * The negative space of an agent's behavior.
     *
     * @param silentEvents    Events the agent was present for but didn't respond to
     * @param silenceRate     Fraction of events in agent's rooms with no agent response (0.0-1.0)
     * @param avoidedRooms    Rooms the agent left quickly or never entered (from available exits)
     * @param topicSilences   Topics raised by others that the agent consistently ignored
     * @param responseGaps    Periods where agent was present but inactive (millisecond durations)
     */
    public record NegativeSpace(
        @JsonProperty("silentEvents") int silentEvents,
        @JsonProperty("silenceRate") float silenceRate,
        @JsonProperty("avoidedRooms") List<String> avoidedRooms,
        @JsonProperty("topicSilences") Map<String, Integer> topicSilences,
        @JsonProperty("responseGaps") List<Long> responseGaps
    ) {
        @JsonCreator
        public NegativeSpace {}

        public static NegativeSpace empty() {
            return new NegativeSpace(0, 0.0f, List.of(), Map.of(), List.of());
        }
    }

    /**
     * Analyze an agent's negative space from event history.
     *
     * @param agentEntityId  The agent's entity ID
     * @param agentEvents    Events generated BY this agent
     * @param roomEvents     ALL events in rooms where this agent was present
     * @return NegativeSpace analysis
     */
    public static NegativeSpace analyze(String agentEntityId,
                                          List<WorldEvent> agentEvents,
                                          List<WorldEvent> roomEvents) {
        if (roomEvents == null || roomEvents.isEmpty()) {
            return NegativeSpace.empty();
        }

        // Collect timestamps where agent actually responded (said something)
        Set<String> agentRoomTimestamps = new HashSet<>();
        Set<String> agentRooms = new HashSet<>();
        for (var event : agentEvents) {
            agentRoomTimestamps.add(event.roomId() + "|" + event.timestamp().toEpochMilli() / 5000);
            agentRooms.add(event.roomId());
        }

        // Count events agent was present for but didn't respond to
        // "Present" = agent had events in same room within a 5-second window
        int totalRoomEvents = 0;
        int silentEvents = 0;
        Map<String, Integer> topicSilences = new HashMap<>();

        // Track rooms seen in roomEvents but agent never acted in
        Set<String> allRooms = new HashSet<>();

        // Track response gaps
        List<Long> responseGaps = new ArrayList<>();
        long lastAgentEventMs = -1;

        for (var event : roomEvents) {
            allRooms.add(event.roomId());

            // Skip agent's own events
            if (event instanceof WorldEvent.Said said && said.entityId().equals(agentEntityId)) {
                if (lastAgentEventMs > 0) {
                    long gap = said.timestamp().toEpochMilli() - lastAgentEventMs;
                    if (gap > 0) responseGaps.add(gap);
                }
                lastAgentEventMs = said.timestamp().toEpochMilli();
                continue;
            }

            // Only count Said events from others (conversations the agent could have joined)
            if (event instanceof WorldEvent.Said otherSaid) {
                totalRoomEvents++;
                String timeWindow = event.roomId() + "|" + event.timestamp().toEpochMilli() / 5000;
                // Check if agent was active in this room at this time
                if (agentRooms.contains(event.roomId())) {
                    // Agent was in this room at some point — did they respond near this event?
                    if (!agentRoomTimestamps.contains(timeWindow)) {
                        silentEvents++;
                        // Extract simple topic signal from the text
                        extractTopicWords(otherSaid.text()).forEach(topic ->
                            topicSilences.merge(topic, 1, Integer::sum));
                    }
                }
            }
        }

        float silenceRate = totalRoomEvents > 0 ? (float) silentEvents / totalRoomEvents : 0.0f;

        // Rooms the agent could see (appeared in roomEvents) but never acted in
        List<String> avoidedRooms = allRooms.stream()
            .filter(r -> !agentRooms.contains(r))
            .sorted()
            .collect(Collectors.toList());

        // Only keep topics with multiple silences (filtering noise)
        Map<String, Integer> significantSilences = topicSilences.entrySet().stream()
            .filter(e -> e.getValue() >= 2)
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

        return new NegativeSpace(silentEvents, silenceRate, avoidedRooms,
            Map.copyOf(significantSilences),
            responseGaps.size() > 100 ? responseGaps.subList(0, 100) : List.copyOf(responseGaps));
    }

    /**
     * Extract simple topic words from text (heuristic, no LLM).
     * Returns lowercase words > 4 chars, excluding common stop words.
     */
    static List<String> extractTopicWords(String text) {
        if (text == null || text.isBlank()) return List.of();
        return Arrays.stream(text.toLowerCase().split("\\W+"))
            .filter(w -> w.length() > 4)
            .filter(w -> !STOP_WORDS.contains(w))
            .distinct()
            .limit(5)
            .collect(Collectors.toList());
    }

    private static final Set<String> STOP_WORDS = Set.of(
        "about", "above", "after", "again", "against", "along",
        "being", "below", "between", "could", "doing", "during",
        "every", "going", "great", "having", "maybe", "might",
        "never", "other", "really", "right", "shall", "should",
        "since", "still", "their", "there", "these", "thing",
        "think", "those", "under", "until", "using", "where",
        "which", "while", "would", "yours"
    );
}
