package org.wyrdsekai.common.protocol;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.JsonNode;
import org.wyrdsekai.common.model.ContentBlock;
import org.wyrdsekai.common.model.Hint;
import org.wyrdsekai.common.model.RoomObject;
import org.wyrdsekai.common.model.RoomSnapshot;
import org.wyrdsekai.common.model.Structured;
import org.wyrdsekai.common.model.TopologySnapshot;

import java.util.List;

/**
 * Server → Client WebSocket messages.
 * Each message carries a seq (monotonically increasing per session) for reconnection replay.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = S2CMessage.RoomState.class, name = "room_state"),
    @JsonSubTypes.Type(value = S2CMessage.Prose.class, name = "prose"),
    @JsonSubTypes.Type(value = S2CMessage.AgentAction.class, name = "agent_action"),
    @JsonSubTypes.Type(value = S2CMessage.StateChange.class, name = "state_change"),
    @JsonSubTypes.Type(value = S2CMessage.ReplayDone.class, name = "replay_done"),
    @JsonSubTypes.Type(value = S2CMessage.Error.class, name = "error"),
    @JsonSubTypes.Type(value = S2CMessage.Notification.class, name = "notification"),
    @JsonSubTypes.Type(value = S2CMessage.Transit.class, name = "transit"),
    @JsonSubTypes.Type(value = S2CMessage.TokenStream.class, name = "token_stream"),
    @JsonSubTypes.Type(value = S2CMessage.TopologyChanged.class, name = "topology_changed"),
    @JsonSubTypes.Type(value = S2CMessage.MapData.class, name = "map_data"),
    @JsonSubTypes.Type(value = S2CMessage.ZoneResponse.class, name = "zone_response"),
    @JsonSubTypes.Type(value = S2CMessage.VoiceAudio.class, name = "voice_audio"),
})
public sealed interface S2CMessage {

    long seq();

    /** Full room state, sent on entry or reconnect. Includes player inventory if available. */
    record RoomState(long seq, RoomSnapshot room, List<RoomObject> inventory) implements S2CMessage {}

    /**
     * Prose narration — agent speech, descriptions, narrative events.
     *
     * @param speaker    Who is speaking (agent name, "narrator", "system")
     * @param text       The prose text
     * @param hints      Contextual hints (§65.2)
     * @param structured Machine-parseable room data (§66.2), null if not a room description
     * @param priority   "critical", "normal", "ambient" (§66.3)
     * @param lang       BCP 47 language tag (e.g. "en", "es", "ja"), null = English assumed
     */
    /**
     * @param isAiGenerated true if this prose was generated by an AI agent (EU AI Act Article 50)
     * @param blocks        Zone-type-specific content blocks (§83.5). Clients render what they
     *                      understand, fall back to each block's fallback text for the rest.
     * @param voice         nullable — true if this response should be spoken aloud by the client's TTS.
     *                      Null or false means text-only. Backward compatible.
     */
    /**
     * @param style nullable — communication style: "say" (default), "emote", "whisper", "tell".
     *              Null defaults to "say". Backward compatible — old clients ignore this field.
     */
    record Prose(long seq, String speaker, String text,
                 List<Hint> hints, Structured structured,
                 String priority, String lang,
                 boolean isAiGenerated,
                 List<ContentBlock> blocks,
                 Boolean voice,
                 String style) implements S2CMessage {

        /** Backward-compatible constructor — lang defaults to null, not AI-generated, no blocks, no voice, no style. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured, String priority) {
            this(seq, speaker, text, hints, structured, priority, null, false, List.of(), null, null);
        }

        /** Constructor with lang but no AI flag, blocks, voice, or style. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured,
                     String priority, String lang) {
            this(seq, speaker, text, hints, structured, priority, lang, false, List.of(), null, null);
        }

        /** Constructor with lang and style but no AI flag, blocks, or voice. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured,
                     String priority, String lang, String style) {
            this(seq, speaker, text, hints, structured, priority, lang, false, List.of(), null, style);
        }

        /** Constructor with AI flag but no blocks, voice, or style. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured,
                     String priority, String lang,
                     boolean isAiGenerated) {
            this(seq, speaker, text, hints, structured, priority, lang, isAiGenerated, List.of(), null, null);
        }

        /** Constructor with AI flag and blocks but no voice or style. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured,
                     String priority, String lang,
                     boolean isAiGenerated,
                     List<ContentBlock> blocks) {
            this(seq, speaker, text, hints, structured, priority, lang, isAiGenerated, blocks, null, null);
        }

        /** Constructor with AI flag, blocks, and voice but no style. */
        public Prose(long seq, String speaker, String text,
                     List<Hint> hints, Structured structured,
                     String priority, String lang,
                     boolean isAiGenerated,
                     List<ContentBlock> blocks,
                     Boolean voice) {
            this(seq, speaker, text, hints, structured, priority, lang, isAiGenerated, blocks, voice, null);
        }

        /** Check if this response should be spoken aloud. */
        public boolean isVoice() {
            return voice != null && voice;
        }
    }

    /** Agent performed a visible action. */
    record AgentAction(long seq, String agentName, String action,
                       String description) implements S2CMessage {}

    /** Room state changed (object moved, exit opened, etc.). */
    record StateChange(long seq, String description,
                       Structured structured,
                       List<ContentBlock> blocks) implements S2CMessage {

        /** Backward-compatible constructor without blocks. */
        public StateChange(long seq, String description, Structured structured) {
            this(seq, description, structured, List.of());
        }
    }

    /** Reconnect replay complete — client is caught up. */
    record ReplayDone(long seq, long fromSeq, long toSeq, int count) implements S2CMessage {}

    /** Error response to a client request. */
    record Error(long seq, String code, String message, String requestId) implements S2CMessage {}

    /**
     * Response to a zone command (codeplane.status, codeplane.create, etc.).
     * Carries requestId for correlation so clients can match responses to requests
     * even when broadcasts from active pipelines flood the WebSocket.
     *
     * @param requestId  Correlation ID matching the original C2S Command
     * @param namespace  Zone namespace that handled the command (e.g. "codeplane")
     * @param text       Human-readable response text
     * @param data       Structured JSON response data (nullable)
     * @param blocks     Zone-type content blocks (nullable)
     */
    record ZoneResponse(long seq, String requestId, String namespace,
                        String text, JsonNode data,
                        List<ContentBlock> blocks) implements S2CMessage {}

    /** System notification (welcome, maintenance, etc.). */
    record Notification(long seq, String level, String title,
                        String message) implements S2CMessage {}

    /**
     * Transit directive — tells client to reconnect to a remote zone.
     * Sent when agent transit is approved.
     */
    record Transit(long seq, String targetZoneId, String targetUrl,
                   String transitToken, String message) implements S2CMessage {}

    /**
     * Real-time token stream from an agent or companion (§83.6).
     * Lightweight message for token-by-token delivery during inference.
     *
     * @param source  Speaker identity (companion name or agent ID)
     * @param token   Text fragment (typically 1-4 tokens worth)
     * @param done    True on final token — client assembles full text
     * @param context Optional routing context (boardId, roomId), null for common case
     */
    record TokenStream(long seq, String source, String token,
                       boolean done, String context) implements S2CMessage {}

    /**
     * Topology change notification (§N3).
     * Sent when exits open/close or rooms are created/destroyed.
     *
     * @param changeType          "exit_opened", "exit_closed", "room_created", "room_destroyed"
     * @param roomId              Room where the change occurred
     * @param direction           Affected exit direction (null for room create/destroy)
     * @param targetRoomId        Target of the affected exit (null for room create/destroy)
     * @param description         Human-readable description of the change
     */
    record TopologyChanged(long seq, String changeType, String roomId,
                           String direction, String targetRoomId,
                           String description) implements S2CMessage {}

    /**
     * Response to map/nearby/rooms/path/where/exits commands (§N4).
     *
     * @param command   Which command generated this ("map", "nearby", "rooms", "path", "where", "exits")
     * @param textMap   ASCII or accessible text rendering
     * @param topology  Structured topology data for client rendering (null for simple commands)
     * @param path      For "path" command: ordered room IDs from source to destination (null otherwise)
     */
    record MapData(long seq, String command, String textMap,
                   TopologySnapshot topology, List<String> path) implements S2CMessage {}

    /**
     * Synthesized voice audio -- server sends TTS audio for a companion's response.
     * Audio is base64-encoded in JSON for backward compatibility with text WebSocket frames.
     * Sent when server-side TTS is available; otherwise, the client uses its own TTS
     * based on the Prose message with voice=true.
     *
     * @param seq         Sequence number
     * @param audioBase64 Base64-encoded audio data (WAV or raw PCM)
     * @param format      Audio format: "wav", "raw", "opus"
     * @param speaker     Name of the speaking agent/companion
     */
    record VoiceAudio(long seq, String audioBase64, String format,
                      String speaker) implements S2CMessage {}
}
