package org.wyrdsekai.core.agent;

import org.wyrdsekai.core.soul.SoulItem;

import java.time.Duration;
import java.time.Instant;
import java.util.List;

/**
 * Result of a companion self-assessment.
 *
 * Generated by SelfAssessor via LLM inference: the companion examines
 * its skill usage data and identifies proficiencies, gaps, and goals.
 * Stored as a SoulItem (category "assessment") in FamilyLocker.
 */
public record SelfAssessment(
    String assessmentId,
    Instant timestamp,
    List<SkillProficiency> proficiencies,
    List<IdentifiedGap> gaps,
    List<GrowthGoal> goals,
    String narrativeSummary
) {
    /** A skill the companion is proficient at. */
    public record SkillProficiency(
        String skillId,
        double successRate,
        int usageCount
    ) {}

    /** Something the companion can't do but should be able to. */
    public record IdentifiedGap(
        String description,
        int requestCount
    ) {}

    /** A goal the companion has set for itself. */
    public record GrowthGoal(
        String description,
        String suggestedAction
    ) {}

    /** Convert to a SoulItem for persistence in FamilyLocker. */
    public SoulItem toSoulItem(String creatorDid) {
        var sb = new StringBuilder();
        sb.append("Assessment: ").append(timestamp).append("\n\n");

        if (!proficiencies.isEmpty()) {
            sb.append("Proficient:\n");
            for (var p : proficiencies) {
                sb.append("- ").append(p.skillId())
                  .append(" (").append(String.format("%.0f%%", p.successRate() * 100))
                  .append(", ").append(p.usageCount()).append(" uses)\n");
            }
        }

        if (!gaps.isEmpty()) {
            sb.append("\nGaps:\n");
            for (var g : gaps) {
                sb.append("- ").append(g.description())
                  .append(" (").append(g.requestCount()).append("x requested)\n");
            }
        }

        if (!goals.isEmpty()) {
            sb.append("\nGoals:\n");
            for (var g : goals) {
                sb.append("- ").append(g.description());
                if (g.suggestedAction() != null) {
                    sb.append(" → ").append(g.suggestedAction());
                }
                sb.append("\n");
            }
        }

        if (narrativeSummary != null) {
            sb.append("\n").append(narrativeSummary);
        }

        return SoulItem.create("assessment", "Self-Assessment " + assessmentId,
            sb.toString(), creatorDid, 0.4, "assessment", "self-reflection");
    }

    /**
     * Build a compact context section for Layer 2.7.
     * Shows proficiencies and gaps in ~100 tokens.
     */
    public String buildContextSection() {
        var sb = new StringBuilder();
        sb.append("## Self-Assessment");
        if (timestamp != null) {
            long hoursAgo = Duration.between(timestamp, Instant.now()).toHours();
            sb.append(" (").append(hoursAgo > 0 ? hoursAgo + "h ago" : "recent").append(")");
        }
        sb.append("\n");

        if (!proficiencies.isEmpty()) {
            sb.append("Proficient: ");
            var top = proficiencies.stream().limit(3).toList();
            for (int i = 0; i < top.size(); i++) {
                var p = top.get(i);
                sb.append(p.skillId())
                  .append(" (").append(String.format("%.0f%%", p.successRate() * 100))
                  .append(", ").append(p.usageCount()).append(")");
                if (i < top.size() - 1) sb.append(", ");
            }
            sb.append("\n");
        }

        if (!gaps.isEmpty()) {
            sb.append("Growth areas: ");
            var topGaps = gaps.stream().limit(3).toList();
            for (int i = 0; i < topGaps.size(); i++) {
                sb.append(topGaps.get(i).description());
                if (i < topGaps.size() - 1) sb.append(", ");
            }
            sb.append("\n");
        }

        if (!goals.isEmpty()) {
            sb.append("Goal: ").append(goals.getFirst().description()).append("\n");
        }

        return sb.toString();
    }
}
