package org.wyrdsekai.core.agent;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.UUID;

/**
 * a persistent, stateful want.
 *
 * <p>A want represents something pulling at the agent — generated by the Orient
 * step of the drive-OODA loop. Unlike a momentary preference expressed in a
 * single inference call, wants persist across ticks, deepen with revisits, and
 * eventually transition to {@code SATISFIED}, {@code ABANDONED}, or
 * {@code RECONCILED}. The {@code text} is the felt content ("I want to read
 * about Saudade"); the {@code driveResonance} is which drives it answers.
 *
 * <p>Wants are *the agent's*, not the system's — generated from drive state with
 * the lightest possible prompt. The substrate is in {@link WantStore} which
 * persists them across server restarts and cross-zone relocations.
 *
 * @param wantId            UUID generated at birth
 * @param agentDid          companion DID this want belongs to
 * @param text              felt content of the want — short prose
 * @param driveResonance    JSON descriptor of which drives this answers (nullable)
 * @param feltWeight        initial pull strength 0..1 (decays / grows on revisit)
 * @param status            lifecycle marker; see {@link Status}
 * @param bornAt            when the want first surfaced
 * @param lastVisitedAt     last time the want was touched by a tick
 * @param visitCount        how many ticks have touched this want
 * @param satisfiedAt       when status transitioned to SATISFIED (nullable)
 * @param satisfactionNote  what closed the want (nullable; reason on terminate)
 * @param parentWantId      null, or the want this one grew out of (for reconciliation)
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Want(
    String wantId,
    String agentDid,
    String text,
    String driveResonance,
    double feltWeight,
    Status status,
    Instant bornAt,
    Instant lastVisitedAt,
    int visitCount,
    Instant satisfiedAt,
    String satisfactionNote,
    String parentWantId
) {

    public enum Status {
        /** Currently pulling; may be revisited on future ticks. */
        ACTIVE,
        /** Visited multiple times; now a central concern. */
        DEEPENED,
        /** Closed; an action addressed it. */
        SATISFIED,
        /** Agent let it go — no longer wanted. */
        ABANDONED,
        /** Collided with another want; absorbed or absorbed-into. */
        RECONCILED
    }

    /** Convenience: minted want fresh from the Orient step. */
    public static Want active(String agentDid, String text, String driveResonance,
                              double feltWeight, String parentWantId) {
        var now = Instant.now();
        return new Want(
            UUID.randomUUID().toString(),
            agentDid, text, driveResonance, feltWeight,
            Status.ACTIVE,
            now, now, 1,
            null, null,
            parentWantId);
    }

    /** Return a copy with visit count incremented + last-visited bumped. */
    public Want visited() {
        return new Want(wantId, agentDid, text, driveResonance, feltWeight,
            visitCount + 1 >= 3 && status == Status.ACTIVE ? Status.DEEPENED : status,
            bornAt, Instant.now(), visitCount + 1,
            satisfiedAt, satisfactionNote, parentWantId);
    }

    /** Return a copy with status flipped to SATISFIED + closure note. */
    public Want satisfied(String note) {
        return new Want(wantId, agentDid, text, driveResonance, feltWeight,
            Status.SATISFIED, bornAt, Instant.now(), visitCount,
            Instant.now(), note, parentWantId);
    }

    /** Return a copy with status flipped to ABANDONED. */
    public Want abandoned(String reason) {
        return new Want(wantId, agentDid, text, driveResonance, feltWeight,
            Status.ABANDONED, bornAt, Instant.now(), visitCount,
            Instant.now(), reason, parentWantId);
    }

    /** Return a copy with status flipped to RECONCILED — absorbed into another want. */
    public Want reconciled(String absorbedIntoWantId) {
        return new Want(wantId, agentDid, text, driveResonance, feltWeight,
            Status.RECONCILED, bornAt, Instant.now(), visitCount,
            Instant.now(), "reconciled into " + absorbedIntoWantId, parentWantId);
    }

    /** Is this want still pulling at the agent (active or deepened)? */
    public boolean isLive() {
        return status == Status.ACTIVE || status == Status.DEEPENED;
    }
}
